"""empty message

Revision ID: 46df61b2e392
Revises: 47735a62e35a
Create Date: 2021-07-15 11:35:59.537197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46df61b2e392'
down_revision = '47735a62e35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
