"""empty message

Revision ID: 47735a62e35a
Revises: 8030f12480ba
Create Date: 2021-07-13 12:05:38.180984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47735a62e35a'
down_revision = '8030f12480ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('place', sa.String(length=40), nullable=False),
    sa.Column('site', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('place', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education')
    op.drop_table('career')
    # ### end Alembic commands ###
