"""empty message

Revision ID: 6a41065a7c76
Revises: 46df61b2e392
Create Date: 2021-07-16 12:16:36.884447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a41065a7c76'
down_revision = '46df61b2e392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career')
    op.drop_table('education')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('date', sa.VARCHAR(length=30), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('desc', sa.TEXT(), nullable=False),
    sa.Column('place', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('date', sa.VARCHAR(length=30), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('desc', sa.TEXT(), nullable=False),
    sa.Column('place', sa.VARCHAR(length=40), nullable=False),
    sa.Column('site', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
