"""empty message

Revision ID: ae37a878e2e2
Revises: 6a41065a7c76
Create Date: 2021-07-16 12:22:41.202680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae37a878e2e2'
down_revision = '6a41065a7c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tag', sa.String(length=80), nullable=False),
    sa.Column('tech', sa.String(length=80), nullable=False),
    sa.Column('desc', sa.String(length=50), nullable=False),
    sa.Column('info', sa.String(length=80), nullable=False),
    sa.Column('link', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('blog')
    # ### end Alembic commands ###
